version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  azure-aks: circleci/azure-aks@0.3.0
  kubernetes: circleci/kubernetes@1.3.0

jobs:
  aks-deploy:
    executor: azure-aks/default
    parameters:
      cluster-name:
        description: |
          Name of the AKS cluster
        type: string
      resource-group:
        description: |
          Resource group that the cluster is in
        type: string
    steps:
      - checkout
      - run:
          name: Pull Updated code from repo
          command: git pull origin main
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          perform-login: true
          resource-group: << parameters.resource-group >>
      - kubernetes/create-or-update-resource:
          resource-file-path: manifests/nodejs-aks-app.yaml
          resource-name: kustomization/nodejs-aks-app

  bump-docker-tag-kustomize:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install kustomize
          command: |
            URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.5.2/kustomize_v4.5.2_linux_amd64.tar.gz
            curl -L $URL | tar zx
            [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo
            $SUDO chmod +x ./kustomize
            $SUDO mv ./kustomize /usr/local/bin
      - checkout
      - run:
          name: Bump Docker Tag
          command: |
            cd manifests
            kustomize edit set image $nodejs-aks-app=rahulrajeev8/nodejs-aks-app:$CIRCLE_SHA1
            kustomize build . > nodejs-aks-app.yaml
      - add_ssh_keys:
          fingerprints:
            - "eb:96:ad:27:56:e9:62:b9:42:5f:85:0d:df:08:df:6e"
      - run:
          name: Commit & Push to GitHub
          command: |
            git config user.email "rahulrajeev800@gmail.com"
            git config user.name "rahulrajeev5"
            git checkout main           
            git add manifests/nodejs-aks-app.yaml
            git add manifests/kustomization.yaml
            git commit -am "Bumps docker tag [skip ci]"
            git push origin main

workflows:
  Deploy-App-on-AKS:
    jobs:
      - docker/publish:
          image: $rahulrajeev8/nodejs-aks-app
          tag: $CIRCLE_SHA1,latest
      - bump-docker-tag-kustomize:
          requires:
            - docker/publish
      - aks-deploy:
          cluster-name: ECOMMERCE
          resource-group: SRH
          requires:
            - bump-docker-tag-kustomize
